### ISSUE TITLE
collect(::Dictionary) doesn't work

### ISSUE THREAD

**Issue by c42f** [andyferris/Dictionaries.jl#20]
HashDictionary does work, but not Dictionary:

```
julia> d = Dictionaries.Dictionary([1], [:a])
1-element Dictionary{Int64,Symbol,Array{Int64,1},Array{Symbol,1}}
 1 │ :a

julia> collect(d)
ERROR: MethodError: no method matching size(::Dictionary{Int64,Symbol,Array{Int64,1},Array{Symbol,1}})
```

**Comment by andyferris** [comment]
Hmm. This is a `HasLength` iterator. Why is something calling `size` without checking it `HasShape`?

**Comment by andyferris** [comment]
For some reason I wasn't watching/following this repo. Sorry for the delay!

**Comment by c42f** [comment]
It's all good! Not really affecting me directly I was just testing some things out.
