### ISSUE TITLE
`values` printing is strange

### ISSUE THREAD

**Issue by yurivish** [andyferris/Dictionaries.jl#29]
```
julia> using Dictionaries

julia> d = Dictionary([:a], [Dictionary([:b], [:c])])
1-element Dictionary{Symbol,Dictionary{Symbol,Symbol}}
 :a │ {:b │ :c}

julia> values(d)
1-element Dictionary{Symbol,Dictionary{Symbol,Symbol}}
 :a │ {:b │ :c}

julia> collect(values(d))
1-element Array{Dictionary{Symbol,Symbol},1}:
 {:b │ :c}
```

I find it quite surprising that `values(d)` prints the keys of `d` and prints as if `values(d)` has the same type as `d`. The keys don't seem to be present if you `collect` them, however. I'm not sure if this is a bug?

Edit: Once I filed this I had the thought that this might just be a consequence of the fact that a dictionary iterates its values. So I don't even need `values` here.

I guess it's just as strange as `pairs(Dict(:a => :b))` returning the dict itself!

**Comment by andyferris** [comment]
That’s right - the biggest difference between `Dictionary` and `Dict` is what it iterates - here a dictionary is the same as its `values` and in `Base` a dictionary is the same as its `pairs`.

**Comment by yurivish** [comment]
Yep, understood. And I think it’s an excellent design decision. 👍
