### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by Azzaare** [andyferris/Dictionaries.jl#33]
Any plan to implement samplings from `Indices` and `Dictionary`?

**Comment by andyferris** [comment]
Hi @Azzaare - could you give an example of what you mean?

**Comment by Azzaare** [comment]
Thank you for the quick reaction @andyferris 

As for for many collections I would like to draw a random element from a Dictionary `d`  and from an Indices `inds`

Ideally using `rand(d)` that would return a random value of `d` and `rand(inds)` that would return a random key.

So far, the not great workaround I can use is as follows:
```julia
s = Set(inds)
r = rand(s)
# assume d and d2 have the same Indices
return d[r], d2[r]
```

It is not great, and also converting inds into set is not the most efficient.

As there is a specific error for calling rand on Dictionary and Indices, I was wondering if you had any plan for it ^^

**Comment by andyferris** [comment]
Ah yes - now I recall. 

For `Dictionary` or `Indices` I can implement a process that does rejection sampling in tokens. For dense collections it is pretty trivial. For future sorted tree implementations... well if the tree retains indices/counts at the nodes (or is implemented on a contiguous heap) it is possible. 

The question I had is whether there was some kind of generic interface I can build. Perhaps `randtoken` needs to be implemented for each concrete `AbstractIndices`?

**Comment by Azzaare** [comment]
Maybe the implementation of randtoken can be a soft requirement that raise an error stating the requirement when it is not implemented?

And this package just provides implementations for a few specific cases.

How about it ?

**Comment by andyferris** [comment]
Yes - that seems fine - technically all the generic code is a "soft" requirement and there are (hopefully) useful error messages describing methods to be implemented in at least some cases.

**Comment by andyferris** [comment]
See #34.
