### ISSUE TITLE
Feature-request: Support Base.haskey

### ISSUE THREAD

**Issue by schlichtanders** [andyferris/Dictionaries.jl#53]
Hi (sorry for the dense opening of issues, I hope you appreciate my attempt to just help)

Just stumbled upon `Base.haskey`, which is quite standard for `Base.AbstractDict` and makes especially sense for `AbstractDictionary` as well, because the iterator does not go over the keys, but the values, so plain `in` is still not working.

Would be great to have it for completenes

**Comment by schlichtanders** [comment]
Currently falling back to `key in keys(d)`

**Comment by andyferris** [comment]
Nice catch! It was intended to be implemented as `key in keys(d)`, but clearly I forgot to add that. I'll fix that up :)

> sorry for the dense opening of issues, I hope you appreciate my attempt to just help

Don't be sorry - I appreciate the help!

**Comment by andyferris** [comment]
Fixed in the 0.3.10 release.
