### ISSUE TITLE
`dictionary` with mixture of key types

### ISSUE THREAD

**Issue by mtfishman** [andyferris/Dictionaries.jl#77]
Hi Andy, thanks for the great package. We're currently using `Dictionaries.jl` in our dictionary-of-keys data structure in our block sparse tensor type inside ITensors.jl since I found that it is much faster than `Base.Dict` for iteration. I also like that the interface is closer to the `Array` interface, once I started using this package it's tough going back to using `Base.Dict` without getting totally confused by the interface for iteration and other operations.

A small issue I came across is the following:
```julia
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = vim

(@v1.7) pkg> st Dictionaries
      Status `~/.julia/environments/v1.7/Project.toml`
  [85a47980] Dictionaries v0.3.15

julia> d = dictionary(["A" => 1, :B => 2])
ERROR: MethodError: Cannot `convert` an object of type Symbol to an object of type String
Closest candidates are:
  convert(::Type{String}, ::String) at ~/software/julia-1.7.0/share/julia/base/essentials.jl:223
  convert(::Type{T}, ::T) where T<:AbstractString at ~/software/julia-1.7.0/share/julia/base/strings/basic.jl:231
  convert(::Type{T}, ::AbstractString) where T<:AbstractString at ~/software/julia-1.7.0/share/julia/base/strings/basic.jl:232
  ...
Stacktrace:
 [1] gettoken!(d::Dictionary{String, Int64}, i::Symbol)
   @ Dictionaries ~/.julia/packages/Dictionaries/mxSnY/src/insertion.jl:46
 [2] __dictionary(key::typeof(first), value::typeof(last), dict::Dictionary{String, Int64}, iter::Vector{Pair{Any, Int64}}, s::Int64)
   @ Dictionaries ~/.julia/packages/Dictionaries/mxSnY/src/Dictionary.jl:225
 [3] _dictionary(key::typeof(first), value::typeof(last), #unused#::Type{Dictionary}, iter::Vector{Pair{Any, Int64}})
   @ Dictionaries ~/.julia/packages/Dictionaries/mxSnY/src/Dictionary.jl:210
 [4] dictionary(iter::Vector{Pair{Any, Int64}})
   @ Dictionaries ~/.julia/packages/Dictionaries/mxSnY/src/Dictionary.jl:193
 [5] top-level scope
   @ REPL[10]:1
```
I was hoping this would promote the keys to a common data type (in this case `Any`). Instead it looks like it is basing the key type on the first key it sees.

**Comment by andyferris** [comment]
Thanks for the kind words @mtfishman. I'm glad you've found it useful. Back in my quantum tensor network days I found ITensor to be really cool, too!

Huh, yes it is meant to widen the type (I think that's the double underscore version) or use the eltype of the array to figure it out. We'll have to fix this.

**Comment by andyferris** [comment]
Damn, there's a typo in `copy(::AbstractIndices, ::Type)`. I'll fix it.

**Comment by andyferris** [comment]
https://github.com/JuliaRegistries/General/pull/50275

**Comment by andyferris** [comment]
So I was just recalling - back when ITensor was C++ (only) and Julia was version 0.3, I had a stab at bring tensors to Julia: https://github.com/andyferris/Tensors.jl. Fun times!

Anyway hopefully v0.3.16 here will sort out this problem for you.

**Comment by mtfishman** [comment]
Thanks for the quick fix!

I started using Julia around then during my PhD, and coming across packages like yours inspired me to give Julia a try (my thinking was that if serious tensor network people like you and Jutho were using this new language, it must have something to it!).
