### ISSUE TITLE
Performance of getindices significantly slower on Dictionary than Dict

### ISSUE THREAD

**Issue by yurivish** [andyferris/Dictionaries.jl#8]
```jl
julia> using Dictionaries, Random, BenchmarkTools

julia> ks = shuffle(1:20_000);

julia> vs = shuffle(ks);

julia> d1 = Dict(ks .=> vs);

julia> d2 = Dictionary(ks, vs);

julia> @btime getindices(d1, 1:20_000);
  155.533 μs (4 allocations: 156.38 KiB)

julia> @btime getindices(d2, 1:20_000);
  86.961 ms (4 allocations: 156.38 KiB)

julia> @btime getindex.(Ref(d2), 1:20_000);
  86.091 ms (5 allocations: 156.39 KiB)
```

**Comment by andyferris** [comment]
Ahh - keep in mind that `Dictionary` is a simple, non-hash dictionary where lookup is O(N). Use `HashDictionary` for collections larger than 10 or so. (I know, I know, the names in this package are too long...).

I should make this clearer in the README...

**Comment by yurivish** [comment]
Ah, thanks for the clarification!

FWIW, the name `Dictionary` is intuitively so close to the name `Dict` that I'm not sure I would have gone to the README to check if I was doing something wrong, unless you used a `<blink>` tag to make it impossible to ignore... :)

**Comment by andyferris** [comment]
In #23 we have renamed `HashDictionary` to `Dictionary`. The new ordered collections are, unfortunately, up to twice as slow at random lookup than the old implementation (which beats `Dict` by 20%). But these are microseconds not milliseconds below :)

```julia
julia> using Dictionaries, Random, BenchmarkTools

julia> ks = shuffle(1:20_000);

julia> vs = shuffle(ks);

julia> d1 = Dict(ks .=> vs);

julia> d2 = Dictionary(ks, vs);

julia> @btime getindices(d1, 1:20_000);
  168.795 μs (4 allocations: 156.38 KiB)

julia> @btime getindices(d2, 1:20_000);
  347.665 μs (4 allocations: 156.38 KiB)

julia> @btime getindex.(Ref(d2), 1:20_000);
  358.608 μs (5 allocations: 156.39 KiB)
```
