### ISSUE TITLE
[Security] Workflow test.yml is using vulnerable action julia-actions/julia-uploadcodecov

### ISSUE THREAD

**Issue by igibek** [andyferris/Dictionaries.jl#82]
The workflow test.yml is referencing action julia-actions/julia-uploadcodecov using references latest. However this reference is missing the commit [16d1c3dcfb192741c59a412870da1fa0ba822d3c](https://github.com/julia-actions/julia-uploadcodecov/commits/16d1c3dcfb192741c59a412870da1fa0ba822d3c) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by andyferris** [comment]
Umm, I'm afraid I don't follow
