### ISSUE TITLE
Broadcast from scalar doesn't work (no method matching size)

### ISSUE THREAD

**Issue by Moelf** [andyferris/Dictionaries.jl#94]
while this works:
```julia
dict .*= 0.0
```

this doesn't:
```julia
dict .= 0.0
```

which is very awkward, when you need to set all values to some initial value which is not 0 or 1

a public API for this would be nice:
```julia
dict.values .= 0.0
```

**Comment by andyferris** [comment]
This should be fixed in v0.3.20
